name: flutter_movies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - lib/l10n/en.json
    - lib/l10n/es.json

flutter_gen:
  output: lib/l10n